# -*- coding: utf-8 -*-
"""Instagram Hashtag URL Scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kXR9HFvawXAj83UsCIQtBH9Lk7S7kluc
"""

!pip3 install selenium

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
import pandas as pd
import time

driver = webdriver.Chrome('/Users/SAFIYA ATEEQ/Desktop/chromedriver.exe')
url = "https://www.instagram.com"
# Driver will access to the URL
driver.get(url)

username = WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.CSS_SELECTOR,"input[name='username']")))
password = WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.CSS_SELECTOR,"input[name='password']")))

username.clear()
password.clear()
username.send_keys("instascrape_test")
password.send_keys("xvm6awMF$")

log_in = WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.CSS_SELECTOR,"button[type='submit']"))).click()

query = "realestate"
page = driver.get("https://www.instagram.com/explore/tags/" + query)

driver.execute_script("window.scrollBy(0,1000000)")
time.sleep(5)
driver.execute_script("window.scrollBy(0,1000000)")
time.sleep(5)
driver.execute_script("window.scrollBy(0,1000000)")
time.sleep(5)

links = driver.find_elements_by_tag_name('a')
links = [link.get_attribute('href') for link in links]

df = pd.DataFrame(links,columns=["InstagramPostLink"])
print(df)
df.to_csv('uniqlojapan.csv')